import { FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Check, Send, ShieldCheck, Sparkles } from 'lucide-react';
import { extractInterview, interviewTurn } from '../services/api';

export default function Interview(){
  const [session,setSession]=useState('session-0'); const [input,setInput]=useState(''); const [done,setDone]=useState(false); const [sending,setSending]=useState(false); const [progress,setProgress]=useState(20); const [extracting,setExtracting]=useState(false);
  const [turns,setTurns]=useState<{q:string;a?:string}[]>([{q:'先从整体讲起：这次面试一共有几轮？每一轮大概是什么形式？'}]); const [restored,setRestored]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem('interviewSession'); if(saved){const value=JSON.parse(saved); if(value?.turns?.length){setSession(value.session||'session-0');setTurns(value.turns);setProgress(value.progress||20);setDone(Boolean(value.done));}}}catch{ /* ignore malformed local draft */ } finally{setRestored(true)}},[]);
  useEffect(()=>{if(!restored)return; localStorage.setItem('interviewSession',JSON.stringify({session,turns,progress,done,updatedAt:new Date().toISOString()}));},[restored,session,turns,progress,done]);
  async function submit(e:FormEvent){e.preventDefault(); if(!input.trim()||done||sending)return; const answer=input.trim(); setInput(''); setSending(true); try{const history=turns.flatMap(t=>[{role:'assistant' as const,content:t.q},...(t.a?[{role:'user' as const,content:t.a}]:[])]); const reply=await interviewTurn(session,answer,history); const nextProgress=Math.min(100,progress+20); const shouldFinish=reply.done||nextProgress>=100; setSession(reply.sessionId); setTurns(t=>[...t.slice(0,-1),{...t[t.length-1],a:answer},...(shouldFinish?[]:[{q:reply.question}])]); setDone(shouldFinish); setProgress(nextProgress); if(shouldFinish){setExtracting(true); await extractInterview(reply.sessionId); setExtracting(false);}}catch{setExtracting(false)}finally{setSending(false)}}
  return <section className="page section narrow wide-top"><div className="progress modern"><span className="active">1 背景</span><span className="active">2 AI 访谈</span><span className={done?'active':''}>3 知识确认</span><span>4 授权</span></div><div className="interview-head"><div><div className="eyebrow"><Sparkles size={13}/> AI INTERVIEW SESSION</div><h1>像聊天一样，把真正记得的细节讲出来</h1><p className="muted">AI 会继续追问关键节点，并把回答整理成面试轮次、问题、答案、反思与建议。</p></div><div className="session-progress"><b>{Math.min(progress,100)}%</b><span>访谈进度</span></div></div><div className="interview-card fresh-card">{turns.map((t,i)=><div className="turn" key={i}><div className="ai-q"><span>AI</span><p>{t.q}</p></div>{t.a&&<div className="human-a"><p>{t.a}</p></div>}</div>)}{!done?<form className="interview-composer" onSubmit={submit}><textarea rows={4} value={input} onChange={e=>setInput(e.target.value)} placeholder="直接像聊天一样回答即可…"/><button className="send-btn" disabled={sending||!input.trim()}>{sending?<span className="loader"/>:<Send size={18}/>}</button></form>:<div className="done-card"><Check size={26}/><div><strong>{extracting?'正在整理结构化知识…':'访谈完成，已生成知识条目草稿'}</strong><p>你可以在下一步编辑、隐藏或删除内容，再决定哪些经验授权给 Agent。</p></div></div>}</div><div className="consent-preview"><ShieldCheck size={18}/><span>访谈原文不会自动公开；只有你确认授权后的知识条目才能进入 Agent Retrieval。</span></div>{done&&<Link className="btn primary big" to="/dashboard">查看知识与授权控制</Link>}</section>;
}
